version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: client
    ports:
      - "3306:3306"
    networks:
      - microservice_network
    healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          retries: 10
          timeout: 15s
  app:
    build: .
    container_name: my_microservice
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/client?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge
